% make_EC01M_SFunction.m
% Run this script from the MATLAB Command Window to compile the S-Function.
%
% Prerequisites:
%   1. MATLAB + Simulink + Simulink Desktop Real-Time toolbox installed
%   2. MSVC compiler configured (run: mex -setup C++)
%   3. NEXTWUSBLib.lib + NEXTWUSBLib.h accessible at the paths below

fprintf('Building EC01M_SFunction.mex (64-bit Windows)...\n');

mex('-R2018a',...
    'EC01M_SFunction.cpp', ...
    'NEXTWUSBLib.cpp', ...
    '-lwinusb',...
    '-lsetupapi',...
    '-lcfgmgr32',...
    'COMPFLAGS=$COMPFLAGS /EHsc /W3', ...
    'LINKFLAGS=$LINKFLAGS /SUBSYSTEM:WINDOWS');

fprintf('Build complete: EC01M_SFunction.mexw64\n');